# config/packages/security.yaml
security:
  role_hierarchy:
    ROLE_SUPER_ADMIN: ['ROLE_ADMIN']
    ROLE_ADMIN: ['ROLE_MANAGER']
    ROLE_MANAGER: ['ROLE_USER']
    ROLE_COMMERCIAL: ['ROLE_USER']
    ROLE_USER: ['ROLE_USER']
    ROLE_DEV: ['ROLE_DEV']
    ROLE_DEPOT: ['ROLE_DEPOT']
    ROLE_CONDUCTEUR_TRAVAUX: ['ROLE_CONDUCTEUR_TRAVAUX']

  enable_authenticator_manager: true

  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    App\Entity\User:
      algorithm: auto

  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      lazy: true
      provider: app_user_provider
      custom_authenticator: App\Security\AppUserAuthenticator
      logout:
        path: app_logout
      remember_me:
        secret: '%kernel.secret%' 
        lifetime: 604800 # 1 week in seconds
        always_remember_me: true
      # Setting the entry point to redirect to the /accueil page
      entry_point: App\Security\AppUserAuthenticator # Your custom authenticator
      
  access_control:
    # Public access to certain pages such as login
    - { path: ^/login, roles: PUBLIC_ACCESS, requires_channel: https }
    - { path: ^/realisations, roles: PUBLIC_ACCESS, requires_channel: https }
    - { path: ^/accueil, roles: PUBLIC_ACCESS, requires_channel: https }
    - { path: ^/details, roles: PUBLIC_ACCESS, requires_channel: https }
    - { path: ^/J4R-ÉCHAFAUDAGES, roles: PUBLIC_ACCESS, requires_channel: https }
    - { path: ^/contact, roles: PUBLIC_ACCESS, requires_channel: https }
    
    # Secure other pages that require authentication
    - { path: ^/admin, roles: ROLE_ADMIN, requires_channel: https }
    - { path: ^/dashboard, roles: ROLE_USER, requires_channel: https }
    
    # Allow anonymous access to certain public pages
    - { path: ^/public, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
    
    # By default, secure all other pages, requiring full authentication
    - { path: ^/, roles: IS_AUTHENTICATED_FULLY, requires_channel: https }

# Test environment-specific settings
when@test:
  security:
    password_hashers:
      Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
        algorithm: auto
        cost: 4
        time_cost: 3
        memory_cost: 10
